// Code generated by go generate; DO NOT EDIT.
// This file contains build info.
//go:build generated

package main

import (
	"github.com/Fuonder/metriccoll.git/internal/buildinfo"
)

var (
	buildVersion = "N/A"
	buildDate    = "N/A"
	buildCommit  = "N/A"
)

var GeneratedBuildInfo = &buildinfo.BuildInfo{
	BuildVersion: "Generated-v0.1.20-rc2-17-g38a1eb7-dirty",
	BuildCommit:  "38a1eb7",
	BuildDate:    buildinfo.MustParseTime("2025-05-27T09:35:56Z"),
	Compiler:     "go1.24.1",
}
