// Code generated by go generate; DO NOT EDIT.
// This file contains build info.
//go:build generated

package main

import (
	"github.com/Fuonder/metriccoll.git/internal/buildinfo"
)

var (
	buildVersion = "N/A"
	buildDate    = "N/A"
	buildCommit  = "N/A"
)

var GeneratedBuildInfo = &buildinfo.BuildInfo{
	BuildVersion: "Generated-v0.1.20-rc2-3-g0c0cb87-dirty",
	BuildCommit:  "0c0cb87",
	BuildDate:    buildinfo.MustParseTime("2025-05-19T19:29:23Z"),
	Compiler:     "go1.23.4",
}
